#!/bin/sh
NAME="pack"
NAME_LONG="pack (OSle Packer)"
VERSION="v0.1.0"

print_info() {
  cat << EOF
Usage: $NAME BINARY [IMAGE]
Add OSle programs into an OSle image.

Pack BINARY into IMAGE. If IMAGE is not provided, it defaults to "osle.img".

  -h, --help         display this help and exit
  -v, --version      output version information and exit

Examples:
  $NAME program.bin              Pack program.bin into osle.img
  $NAME program.bin myos.img     Pack program.bin into myos.img

Report bugs to: https://github.com/shikaan/osle/issues
OSle home page: <https://github.com/shikaan/osle>
EOF
  exit 0
}

print_usage() {
  cat << EOF
Usage: $NAME BINARY [IMAGE]
Try '$NAME --help' for more information.
EOF
  exit 1
}

error() {
  echo "$NAME: $1" >&2
  print_usage
}

### MAIN

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      print_info
      ;;
    -v|--version)
      echo "$NAME_LONG $VERSION"
      exit 0
      ;;
    -*)
      error "unknown option: $1"
      ;;
    *)
      if [ -z "$binary" ]; then
        binary="$1"
      else
        osle="$1"
      fi
      ;;
  esac
  shift
done

if [ -z "$osle" ]; then
  osle="osle.img"
fi

if [ ! -f "$osle" ]; then
  error "unable to find OSle image at ${osle}"
fi

if [ -z "$binary" ]; then
  error "missing required binary argument"
fi

if [ ! -f "$binary" ]; then
  error "unable to find binary at ${binary}"
fi

BLOCK_SIZE=512
FILE_BLOCKS=36
TOTAL_BLOCKS=2880

temp_file=$(mktemp)

block=0
while [ "$block" -lt "$TOTAL_BLOCKS" ]; do
  # Extract the current chunk to check if it's empty
  dd if="$osle" of="$temp_file" bs=$BLOCK_SIZE skip=$block count=$FILE_BLOCKS 2>/dev/null
  
  if [ "$(od -v -An -tx1 "$temp_file" | tr -d ' 0\n')" = "" ]; then
    dd if="$binary" of="$osle" bs=$BLOCK_SIZE seek=$block conv=notrunc
    rm "$temp_file"
    exit 0
  fi
  
  block=$((block + FILE_BLOCKS))
done

echo "$NAME: unable to find an empty block in $osle"
rm "$temp_file"
exit 1
